# Generated by Django 5.2 on 2026-04-04 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('AC', 'Ação'), ('CO', 'Comédia'), ('DR', 'Drama'), ('TE', 'Terror'), ('FI', 'Ficção Científica'), ('RO', 'Romance')], max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='duracao_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Duração total em segundos (ex: 7200 para 2 horas)', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0.0 a 10.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='filme',
            name='categorias',
            field=models.ManyToManyField(related_name='filmes', to='filmes.categoria'),
        ),
    ]
