# Generated by Django 5.2 on 2026-04-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_filme_duracao_segundos_filme_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('AC', 'Ação'), ('CO', 'Comédia'), ('DR', 'Drama'), ('TE', 'Terror'), ('FI', 'Ficção Científica'), ('RO', 'Romance'), ('SU', 'Suspense'), ('AV', 'Aventura'), ('FA', 'Fantasia'), ('MI', 'Misterio'), ('CR', 'Criminal')], max_length=2, unique=True),
        ),
    ]
